project:
  type: book
  output-dir: docs

book:
  title: "IDEAS"
  author: "Sylvain Schmitt"
  date: last-modified
  chapters:
    - index.qmd
    - forest.qmd
    - temperature.qmd
    - precipitation.qmd
    - large_pr.qmd
    - large_tas.qmd
  appendices:
    - literature.qmd
    - meetings.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-fold: false
    number-depth: -1

editor: visual
