# CHELSA {.unnumbered}

> TerraClimate could be used to get to 0.04° (\~4km) instead of CHIRPS 0.05°.

```{r setup}
#| include: false
rm(list = ls()) ; invisible(gc()) ; set.seed(42)
library(tidyverse)
library(terra)
library(sf)
library(leaflet)
theme_set(bayesplot::theme_default())
knitr::opts_chunk$set(
  echo = F, message = F, warning = F, fig.height = 6, fig.width = 8,
  cache = T, cache.lazy = F)
```

```{r data}
#| include: false

capricho <- st_read("data/capricho/capricho.shp")
chirps_r <- rast("results/data/chelsa_capricho.nc")
chirps <- as.data.frame(chirps_r, xy = T) %>% 
  gather(time_num, precipitation, -x, -y) %>% 
  separate(time_num, c("name", "time_num"), convert = T) %>% 
  select(-name) %>% 
  mutate(time = time(chirps_r)[time_num]) %>% 
  select(-time_num)
```

```{r}
chirps %>% 
  mutate(month = month(time)) %>% 
  ggplot(aes(month, precipitation)) +
  annotate("rect", xmin = 0.5, xmax = 2.5, fill  = "#fff4e0",
           ymin = -Inf, ymax = Inf, alpha = 0.5) +
  annotate("rect", xmin = 11.5, xmax = 12.5, fill  = "#fff4e0",
           ymin = -Inf, ymax = Inf, alpha = 0.5) +
  geom_hline(yintercept = 100, col = "lightblue") +
  geom_boxplot(aes(group = as.factor(month))) +
  geom_smooth() +
  theme_bw() +
  xlab("") + ylab("Precipitation (mm/month)") +
  scale_x_continuous(breaks = 1:12,
                   labels = c("J", "F", "M", "A", "M", "J", "J", "A", "S", "O", "N", "D")) +
  ggtitle("Capricho seasonality")
```

```{r}
chirps %>% 
  group_by(x, y, year = year(time)) %>% 
  summarise(precipitation = sum(precipitation)) %>% 
  ggplot(aes(year, precipitation/10^3)) +
  geom_boxplot(aes(group = as.factor(year))) +
  geom_smooth(method = "lm") +
  theme_bw() +
  xlab("") + ylab("Precipitation (m/year)") +
  ggtitle("Capricho interannual variability")
```

```{r}
chirps %>% 
  filter(month(time) %in% c(1, 2, 12)) %>% 
  group_by(x, y, year = year(time)) %>% 
  summarise(precipitation = sum(precipitation)) %>% 
  ggplot(aes(year, precipitation)) +
  geom_boxplot(aes(group = as.factor(year))) +
  geom_smooth(method = "lm") +
  theme_bw() +
  xlab("") + ylab("Precipitation (mm/year)") +
  ggtitle("Capricho dry-season interannual variability")
```

```{r}
chirps %>% 
  filter(!(month(time) %in% c(1, 2, 12))) %>% 
  group_by(x, y, year = year(time)) %>% 
  summarise(precipitation = sum(precipitation)) %>% 
  ggplot(aes(year, precipitation)) +
  geom_boxplot(aes(group = as.factor(year))) +
  geom_smooth(method = "lm") +
  theme_bw() +
  xlab("") + ylab("Precipitation (mm/year)") +
  ggtitle("Capricho wet-season interannual variability")
```

```{r}
chirps %>% 
  filter(month(time) %in% c(1, 2, 12)) %>% 
  group_by(x, y, year = year(time)) %>% 
  summarise(precipitation = sum(precipitation)) %>% 
  ggplot(aes(year, precipitation)) +
  geom_boxplot(aes(group = as.factor(year))) +
  geom_smooth(method = "lm") +
  theme_bw() +
  xlab("") + ylab("Precipitation (mm/year)") +
  ggtitle("Capricho dry-season interannual variability")
```

```{r}
chirps %>% 
  filter(month(time) == 1) %>% 
  group_by(x, y, year = year(time)) %>% 
  summarise(precipitation = sum(precipitation)) %>% 
  ggplot(aes(year, precipitation)) +
  geom_boxplot(aes(group = as.factor(year))) +
  geom_smooth(method = "lm") +
  theme_bw() +
  xlab("") + ylab("Precipitation (mm/year)") +
  ggtitle("Capricho january interannual variability")
```

```{r}
chirps %>% 
  filter(month(time) == 1) %>% 
  group_by(year = year(time)) %>% 
  mutate(anomaly = precipitation - mean(precipitation)) %>% 
  group_by(x, y) %>% 
  summarise(anomaly = mean(anomaly)) %>% 
  ggplot(aes(x, y, fill = anomaly)) +
  geom_raster() +
  theme_void() +
  coord_equal() +
  scale_fill_viridis_c("Mean january\nanomaly (mm)")
```

```{r}
chirps %>% 
  group_by(x, y, year = year(time)) %>% 
  summarise(precipitation = sum(precipitation)) %>% 
  group_by(year) %>% 
  mutate(anomaly = precipitation - mean(precipitation)) %>% 
  group_by(x, y) %>% 
  summarise(anomaly = mean(anomaly)) %>% 
  ggplot(aes(x, y, fill = anomaly)) +
  geom_raster() +
  theme_void() +
  coord_equal() +
  scale_fill_viridis_c() +
  scale_fill_viridis_c("Mean annual\nanomaly (mm)")
```

```{r}
anom <- chirps %>% 
  group_by(x, y, year = year(time)) %>% 
  summarise(precipitation = sum(precipitation)) %>% 
  group_by(year) %>% 
  mutate(anomaly = precipitation - mean(precipitation)) %>% 
  group_by(x, y) %>% 
  summarise(anomaly = mean(anomaly)) 
anom_r <- chirps_r[[1]]
values(anom_r) <- anom$anomaly
pal <- colorNumeric(c("red", "#FFFFCC", "#0C2C84"), values(anom_r), na.color = "transparent")
leaflet() %>% 
  addTiles() %>%
  addRasterImage(anom_r, colors = pal, opacity = 0.6) %>% 
  addPolygons(data = capricho, fill = NA) %>% 
  addLegend(pal = pal, values = values(anom_r),
                  title = "Anomaly")
```
