# Introduction {.unnumbered}

My participation into the [IDEAS project](https://ur-forets-societes.cirad.fr/dans-le-monde/projets-de-recherche/ideas) - Investigación y Desarrollo para la Estabilización de la frontera Agropecuaria en Colombia. The aim is to build climate indices related to land use change in Capricho (red). We will work at two scales: Capricho & the North-West of the Amazon forest.

```{r setup}
#| include: false
rm(list = ls()) ; invisible(gc()) ; set.seed(42)
library(tidyverse)
library(terra)
library(sf)
library(OpenStreetMap)
theme_set(bayesplot::theme_default())
knitr::opts_chunk$set(
  echo = F, message = F, warning = F, fig.height = 6, fig.width = 8,
  cache = T, cache.lazy = F)
```

```{r data}
#| include: false
capricho <- st_read("data/capricho/capricho.shp")
guaviare <- st_read("results/area/Guaviare/Guaviare.shp") %>% 
  st_set_crs(crs(capricho))
amazonia <- st_read("data/Límite_de_la_Amazonia_colombiana._Escala _1 100.000/L%C3%ADmite_de_la_Amazonia_colombiana._Escala%3A_1%3A100.000.shp") %>% 
  st_transform(crs(capricho))
forest <-  rast("results/data/tmf_deforested_2022_2000.tif")
forest_pal <- c("#48712d", "#e40400")
```

```{r amazonmap}

ggplot() +
  tidyterra::geom_spatraster(data = forest) +
  scale_fill_gradient(low = forest_pal[1], high = forest_pal[2], expression(km^2), na.value = NA) +
  geom_sf(data = amazonia, fill = NA, linewidth = 1.5) +
  geom_sf(data = guaviare, fill = NA, linewidth = 1.5) +
  geom_sf(data = capricho, fill = NA, linewidth = 1.5, col = "red") +
  theme_bw()
```
