# Land use {.unnumbered}

```{r setup}
#| include: false
rm(list = ls()) ; invisible(gc()) ; set.seed(42)
library(tidyverse)
library(terra)
library(sf)
library(leaflet)
theme_set(bayesplot::theme_default())
knitr::opts_chunk$set(
  echo = F, message = F, warning = F, fig.height = 6, fig.width = 8,
  cache = T, cache.lazy = F)
```

```{r}
#| eval: false
#| include: false
guaviare <- st_read("data/guaviare/guaviare.shp")
tmf_raw <- list.files("data/JRC_TMF_AnnualChange_v1_SAM_ID47_N10_W80/forobs/products/tmf_v1/AnnualChange/",
           full.names = TRUE) %>% 
  rast()
tmf <- crop(tmf_raw, vect(guaviare))
writeRaster(tmf, "results/data/tmf_capricho.tif")
guaviare <- st_read("data/guaviare/guaviare.shp")
tmf_files <- list.files("data/JRC_TMF_AnnualChange_v1_SAM_ID47_N10_W80/forobs/products/tmf_v1/AnnualChange/", 
                        full.names = TRUE)
get_surf <- function(file)
  rast(file) %>% 
  crop(vect(guaviare)) %>% 
  as.data.frame() %>% 
  gather(year, class) %>% 
  group_by(class) %>% 
  summarise(N = n()) %>% 
  mutate(surface = N*0.5)
stats <- lapply(tmf_files, get_surf) %>% 
  bind_rows()
stats %>% 
  filter(class != 0) %>% 
  mutate(year = rep(1990:2022, each=6)) %>% 
  mutate(surface = N*10^2*10^-6) %>% 
  mutate(type = recode(as.character(class),
         "1" = "Undisturbed tropical moist forest",
         "2" = "Degraded tropical moist forest",
         "3" = "Deforested land",
         "4" = "Tropical moist forest regrowth",
         "5" = "Permanent and seasonal water",
         "6" = "Other land cover")) %>% 
  write_tsv("results/data/tmf_capricho.tsv")
```

```{r data}
#| include: false
tmf <- read_tsv("results/data/tmf_capricho.tsv")
```

```{r}
tmf %>% 
  filter(class != 1) %>% 
  ggplot(aes(year, surface, col = type)) +
  geom_line() +
  theme_bw() +
  xlab("") + ylab(expression(Surface~km^2)) +
  ggtitle("JRC - Tropical Moist Forests", "Guiavare bouding box (not masked)")
```
