# Temperature {.unnumbered}

```{r setup}
#| include: false
rm(list = ls()) ; invisible(gc()) ; set.seed(42)
library(tidyverse)
library(terra)
library(sf)
library(leaflet)
theme_set(bayesplot::theme_default())
knitr::opts_chunk$set(
  echo = F, message = F, warning = F, fig.height = 6, fig.width = 8,
  cache = T, cache.lazy = F)
```

```{r}
area <- st_read("data/guaviare/guaviare.shp", quiet=T)
temp_r <- rast("results/data/modis_guaviare.nc")
ggplot() +
  tidyterra::geom_spatraster(data = temp_r[["tas"]]) +
  theme_bw() +
  scale_fill_viridis_c(expression(delta~T)) +
  geom_sf(data = area, fill = NA, linewidth = 2) +
  ggtitle("Guiavare January Temperature anomaly", 
          "2015-2020 versus 2001-2006 from MODIS MOD11A2 LST")
```

```{r}
area <- st_read("data/guaviare/guaviare.shp", quiet=T)
forest_r <- rast("results/data/hansen_guaviare.nc")
ggplot() +
  tidyterra::geom_spatraster(data = forest_r) +
  theme_bw() +
  scale_fill_viridis_c("loss") +
  geom_sf(data = area, fill = NA, linewidth = 2) +
  ggtitle("Guiavare forest loss", 
          "2022 versus 2000 from Hansen Global Forest Change")
```

```{r}
temp_r <- rast("results/data/modis_guaviare.nc")
forest_r <- rast("results/data/hansen_guaviare.nc")
data.frame(values(temp_r$tas), values(forest_r)) %>% 
  filter(loss < 0.5) %>% 
  na.omit() %>% 
  mutate(loss_class = cut(loss, breaks = seq(0, 1, by = 0.1))) %>% 
  na.omit() %>% 
  ggplot() +
  geom_boxplot(aes(loss_class, tas)) +
  geom_smooth(aes(loss_class, tas)) +
  theme_bw() +
  ggpubr::stat_anova_test(aes(loss_class, tas))
```

```{r}
#| include: false
tmf_2001 <- rast("data/JRC_TMF_AnnualChange_v1_SAM_ID47_N10_W80/forobs/products/tmf_v1/AnnualChange/JRC_TMF_AnnualChange_v1_2001_SAM_ID47_N10_W80.tif") %>% crop(area)
msk <- ifel(tmf_2001 != 1, NA, 1)
tmf_2020 <- rast("data/JRC_TMF_AnnualChange_v1_SAM_ID47_N10_W80/forobs/products/tmf_v1/AnnualChange/JRC_TMF_AnnualChange_v1_2020_SAM_ID47_N10_W80.tif") %>% crop(area) %>% mask(msk) %>% as.factor() %>% resample(temp_r)
```

```{r}
ggplot() +
  tidyterra::geom_spatraster(data = tmf_2020) +
  theme_bw() +
  scale_fill_viridis_d("type") +
  geom_sf(data = area, fill = NA, linewidth = 2) +
  ggtitle("Guiavare forest loss", 
          "2020 versus 2001 from JRC TMF")
```

```{r}
data <- as.data.frame(temp_r, xy = T) %>% 
  left_join(as.data.frame(tmf_2020, xy = T)) %>% 
  na.omit() %>% 
  mutate(type = recode(as.character(Dec2020),
                       "1" = "Undisturbed tropical moist forest",
                       "2" = "Degraded tropical moist forest",
                       "3" = "Deforested land",
                       "4" = "Tropical moist forest regrowth",
                       "5" = "Permanent and seasonal water",
                       "6" = "Other land cover")) %>% 
  filter(Dec2020 != 5)
```

```{r}
data %>% 
  gather(variable, value, -x, -y, -Dec2020, -type) %>% 
  ggplot(aes(type, value, fill = type)) +
  geom_boxplot() +
  theme_bw() +
  ggpubr::stat_anova_test() +
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank(),
        legend.position = "bottom") +
  facet_wrap(~ variable)
```

```{r}
TukeyHSD(aov(tas ~ type, data))$type %>% 
  knitr::kable()
```

```{r}
data$res_tas <- residuals(aov(tas ~ type, data))
data2 <- sample_n(data, 1000)
cor <- pgirmess::correlog(data.frame(data2$x, data2$y), data2$res_tas,
                   method = "Moran", nbclass = 20) %>% 
    as.data.frame()
cor %>% 
  ggplot(aes(x = dist.class*100, y = coef)) + 
  geom_point(aes(alpha = p.value < 0.01)) + geom_line() +
  geom_hline(yintercept = 0) +
  theme_bw() +
  xlab("Distance (km)") + ylab("Moran\'s I")
```

```{r}
mem_vals <- adespatial::mem(spdep::nb2listw(spdep::tri2nb(as.matrix(data2[c("x", "y")])), style = "B"))
data2$mem1 <- mem_vals$MEM1
data2$mem2 <- mem_vals$MEM2
data2$mem3 <- mem_vals$MEM3
m <- lm(tas ~ type + y + mem1 + mem2 + mem3, data2) 
```

```{r}
sjPlot::tab_model(m)
```

```{r}
aov(m) %>% summary()
```

```{r}
data2$res_mem <- residuals(m)
cor <- pgirmess::correlog(data.frame(data2$x, data2$y), data2$res_mem,
                   method = "Moran", nbclass = 20) %>% 
    as.data.frame()
cor %>% 
  ggplot(aes(x = dist.class*100, y = coef)) + 
  geom_point(aes(alpha = p.value < 0.01)) + geom_line() +
  geom_hline(yintercept = 0) +
  theme_bw() +
  xlab("Distance (km)") + ylab("Moran\'s I")
```

```{r}
m <- spaMM::fitme(tas ~ type + Matern(1|y+x), data2)
summary(m)
```

```{r}
cor <- pgirmess::correlog(coords = data2[,c("x", "y")],
                            z = residuals(m),
                            method="Moran", nbclass=20) %>% 
    as.data.frame()
cor %>% 
  ggplot(aes(x = dist.class*100, y = coef)) + 
  geom_point(aes(alpha = p.value < 0.01)) + geom_line() +
  geom_hline(yintercept = 0) +
  theme_bw() +
  xlab("Distance (km)") + ylab("Moran\'s I")
```
